#!/usr/bin/env bash
# Bash script that transfer file from client to server
# using scp

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE
	IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
transefer_file = $1
ip = $2
usr_name = $3
key_path = $4

scp $transfer_file $usr_name@$ip:/~ -i $key_path

