#!/usr/bin/env bash
# Bash script that transfer file from client to server
# using scp

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE
	IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -i "$4" "$1" "$3@$2":~/

