#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sed -i '/location \/ {/c\
	location \/redirect_me {\
		return 301 http://new_page;/
' /etc/nginx/sites-available/default

