#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get install -y nginx
service nginx start
ufw allow 80
echo "Hello World!" | sudo tee /var/www/html/index.html
redirect_me="\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.google.com/;\n\t}"
sed -i "47i\ $redirect_me" /etc/nginx/sites-available/default
service nginx restart
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
page_404="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "47i\ $page_404" /etc/nginx/sites-available/default
sudo service nginx restart
