#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header 
sed -i '/location/a\\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
service nginx restart
