#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

#First install software-properties-common package
apt install --no-install-recommends software-properties-common -y
#Then reference the HAproxy repository, ppa:vbernat/haproxy
add-apt-repository ppa:vbernat/haproxy-2.8
#Update Ubuntu package list
apt update
#Now install HAproxy
apt install haproxy=2.8.* -y
service haproxy start

back="
\nbackend my_backend\n
\tbalance roundrobin\n
\tserver web-01 54.162.48.101:80 check\n
\tserver web-02 100.26.167.222:80 check\n
"
echo -e $back | tee -a /etc/haproxy/haproxy.cfg

front="
frontend my_frontend\n
\tbind 18.206.197.12:80\n
\tmode http\n
\tuse_backend my_backend\n
"
echo -e $front | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
