#!/usr/bin/env bash
#bash script to fix 'not listenning on port 80'
#default port for nginx is 80, but sometimes port 80 is
#assigned to another process so port 8080 will be default
sudo sed -i -e 's/8080/80/g' /etc/nginx/sites-available/default
#sudo sed -i -e 's/server_name/server_name -;/' /etc/nginx/sites-available/defaulta
sudo sed -i -e 's/server_name.*;/server_name -;/g' /etc/nginx/sites-available/default

sudo service nginx restart
