#!/usr/bin/env bash
#Reads the /etc/passwd content and display only the username,
#usr id and home directory path for the file

stopp=true

while $stopp;
do
	cut -d ':' -f 1,3,6 /etc/passwd
	stopp=false
done

