#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.
#Format: The user USERNAME is part of the GROUP_ID gang, lives in 
#HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected
#by the passcode PASSWORD, more info about the user here: USER ID INFO

exec 3< /etc/passwd

while IFS=':' read -r -u 3 -a arr;								
do
	echo "The user ${arr[0]} is part of the ${arr[3]} gang, lives in ${arr[5]} and rides ${arr[6]}. ${arr[2]}'s place is protected by the passcode ${arr[1]}, more info about the user here: ${arr[4]}"
done

