#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

my_list=()
counter=1

until [ $counter -gt 10 ]
do
	my_list[counter]="Best School"
	echo "${my_list[counter]}"
	((counter++))
done
