#!/usr/bin/env bash
# This script display hours from 0 to 12 and minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "hour: ${hour}"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "${minute}"
		((minute++))
	done
	((hour++))
done
