#!/usr/bin/env bash
# This script display hours from 0 to 12 and minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "Hour: ${hour}"
	minute=1
	while [ $minute -le 59 ]
	do

		if [ $hour -eq 12 ]
		then
			break
		fi
		echo "${minute}"
		((minute++))

	done
	((hour++))
done
